In [2]:
from sklearn import linear_model

In [31]:
reg = linear_model.Ridge(alpha=.5)

In [32]:
reg.fit ([[0, 0], [0, 0], [1, 1]], [0, .1, 1] )

Ridge(alpha=0.5, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001)

In [33]:
reg.coef_

array([0.34545455, 0.34545455])

In [34]:
reg.predict([[0, 1], [1, 2],[3,4],[5,6],[7,4],[8,1]] )

array([0.48181818, 1.17272727, 2.55454545, 3.93636364, 3.93636364,
       3.24545455])

In [35]:
reg.intercept_

0.1363636363636364

In [36]:
#lets change ridge with cv

In [37]:
reg1=linear_model.RidgeCV(alphas=[0.1, 1.0, 10.0])

In [40]:
reg1.fit([[0, 0], [0, 0], [1, 1]], [0, .1, 1]) 

RidgeCV(alphas=[0.1, 1.0, 10.0], cv=None, fit_intercept=True, gcv_mode=None,
    normalize=False, scoring=None, store_cv_values=False)

In [41]:
reg1.fit([[0, 0], [0, 0], [1, 1]], [0, .1, 1]) 
reg1.alpha_

0.1

In [43]:
from sklearn import linear_model
las_reg = linear_model.Lasso(alpha=0.1)

In [47]:
las_reg.fit([[0, 0], [1, 1]], [0, 1])

Lasso(alpha=0.1, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

In [50]:
las_reg.predict([[1, 1],[2,2],[3,3]])

array([0.8, 1.4, 2. ])

In [51]:
#lassolars
lassolars_reg = linear_model.LassoLars(alpha=.1)

In [53]:
lassolars_reg.fit([[0, 0], [1, 1]], [0, 1])

LassoLars(alpha=0.1, copy_X=True, eps=2.220446049250313e-16,
     fit_intercept=True, fit_path=True, max_iter=500, normalize=True,
     positive=False, precompute='auto', verbose=False)

In [56]:
lassolars_reg.coef_

array([0.71715729, 0.        ])

In [58]:
#BayesianRidge

In [61]:
X = [[0., 0.], [1., 1.], [2., 2.], [3., 3.]]
Y = [0., 1., 2., 3.]

In [63]:
bayes_reg = linear_model.BayesianRidge()

In [65]:
bayes_reg.fit(X, Y)

BayesianRidge(alpha_1=1e-06, alpha_2=1e-06, compute_score=False, copy_X=True,
       fit_intercept=True, lambda_1=1e-06, lambda_2=1e-06, n_iter=300,
       normalize=False, tol=0.001, verbose=False)

In [67]:
bayes_reg.predict([[1, 0.]])

array([0.50000013])

In [68]:
bayes_reg.coef_

array([0.49999993, 0.49999993])

In [69]:
#polynimal features

In [71]:
from sklearn.preprocessing import PolynomialFeatures
import numpy as np
X = np.arange(6).reshape(3, 2)
X

array([[0, 1],
       [2, 3],
       [4, 5]])

In [75]:
# X = np.arange(6).reshape(3, 2)
# X
poly = PolynomialFeatures(degree=2)
poly.fit_transform(X)

array([[ 1.,  0.,  1.,  0.,  0.,  1.],
       [ 1.,  2.,  3.,  4.,  6.,  9.],
       [ 1.,  4.,  5., 16., 20., 25.]])

In [76]:
#pipeline

In [77]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
import numpy as np
model = Pipeline([('poly', PolynomialFeatures(degree=3)),
                  ('linear', LinearRegression(fit_intercept=False))])
# fit to an order-3 polynomial data
x = np.arange(5)
y = 3 - 2 * x + x ** 2 - x ** 3
model = model.fit(x[:, np.newaxis], y)
model.named_steps['linear'].coef_

array([ 3., -2.,  1., -1.])